//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCode {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetricsAnalizer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclomatic Complexity out of range.
        /// </summary>
        internal static string ComplexityAnalyzerDescription {
            get {
                return ResourceManager.GetString("ComplexityAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity is &apos;{0}&apos;, recomended complexity is {1}.
        /// </summary>
        internal static string ComplexityAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ComplexityAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclomatic Complexity is high.
        /// </summary>
        internal static string ComplexityAnalyzerTitle {
            get {
                return ResourceManager.GetString("ComplexityAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code out of range.
        /// </summary>
        internal static string LinesAnalyzerDescription {
            get {
                return ResourceManager.GetString("LinesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines of of code  is &apos;{0}&apos;, recomended number of parameters is {1}.
        /// </summary>
        internal static string LinesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LinesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code out is high.
        /// </summary>
        internal static string LinesAnalyzerTitle {
            get {
                return ResourceManager.GetString("LinesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters out of range.
        /// </summary>
        internal static string ParametersAnalyzerDescription {
            get {
                return ResourceManager.GetString("ParametersAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters  is &apos;{0}&apos;, recomended number of parameters is {1}.
        /// </summary>
        internal static string ParametersAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ParametersAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters is high.
        /// </summary>
        internal static string ParametersAnalyzerTitle {
            get {
                return ResourceManager.GetString("ParametersAnalyzerTitle", resourceCulture);
            }
        }
    }
}
